### ISSUE TITLE
Further Enhancements

### ISSUE THREAD

**Issue by sajorahasan** [searchy2/CustomAlertViewDialogue#2]
Hello,

I have two request. can you please add it in your library
1) method to set transparent opacity of alertViewDialog.
2) method to set EditText InputType property.

Thank you.

**Comment by searchy2** [comment]
1. In a few weeks, all backgrounds in my Custom UI library will be replaced with realtime blur instead of transparency. 
2. Not feasible. There's a tradeoff between being able to add multiple EditText vs customizing each EditText's functionality. You are welcome to create a new Style with the specific input fields that fit your needs. Very easy!
