### ISSUE TITLE
Dialog backgroud

### ISSUE THREAD

**Issue by TMNMT** [searchy2/CustomAlertViewDialogue#6]
Hi searchy i'd like to thank you for this nice work,
my problem is:
some time when the Simple alert and Confirmation alert dialog start, their backgrounds takes the bottom of the screen as background for short time, like you can see it in the picture
![screenshot_20180424-001127](https://user-images.githubusercontent.com/34405289/39159789-73839c22-475f-11e8-8cb0-b63bbc6e6d00.png)

**Comment by searchy2** [comment]
This happens because the layout is measured twice and redrawn. To prevent this from happening, the background activity's style must be the same as the library's activity style. 

You'll notice that when the popup appears, it enters fullscreen mode. If the background activity isn't in fullscreen mode, then you'll have the background being redrawn.
